### ISSUE TITLE
start wildfly-core-2.0.10.Fina error on window 10

### ISSUE THREAD

**Issue by slieer** [wildfly/wildfly-core#1617]
[INFO] WildFly Core Test Suite: Shared .................... SUCCESS [  4.469 s]
[INFO] WildFly Core Test Suite: Aggregator ................ SUCCESS [  0.078 s]
[INFO] WildFly Core Test Suite: Standalone Integration Tests SUCCESS [  1.693 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:07 min
[INFO] Finished at: 2016-06-17T21:28:50+08:00
[INFO] Final Memory: 98M/1369M
[INFO] ------------------------------------------------------------------------

E:\workspace\sourceCode\wildfly-core-2.0.10.final>.\dist\target\wildfly-core-2.0.10.Final\bin\standalone.bat
Calling "E:\workspace\sourceCode\wildfly-core-2.0.10.final\dist\target\wildfly-core-2.0.10.Final\bin\standalone.conf.bat"
Setting JAVA property to "C:\Program Files\Java\jdk1.8.0_77\bin\java"
===============================================================================

  JBoss Bootstrap Environment

  JBOSS_HOME: "E:\workspace\sourceCode\wildfly-core-2.0.10.final\dist\target\wildfly-core-2.0.10.Final"

  JAVA: "C:\Program Files\Java\jdk1.8.0_77\bin\java"

  JAVA_OPTS: "-Dprogram.name=standalone.bat -Xms64M -Xmx512M -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman"

===============================================================================

07:51:20,638 INFO  [org.jboss.modules] (main) JBoss Modules version 1.5.1.Final
07:51:21,244 INFO  [org.jboss.msc] (main) JBoss MSC version 1.2.6.Final
07:51:21,450 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-6) MSC000001: Failed to start service jboss.as: org.jboss.msc.service.StartException in service jboss.as: Failed to start service
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1904)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ExceptionInInitializerError
        at org.jboss.as.server.ApplicationServerService.start(ApplicationServerService.java:101)
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
        ... 3 more
Caused by: java.lang.IllegalArgumentException: Invalid logger interface org.jboss.as.server.logging.ServerLogger (implementation not found in ModuleClassLoader for Module "org.jboss.as.server:main" from local module loader @2280cdac (finder: local module finder @1517365b (roots: E:\workspace\sourceCode\wildfly-core-2.0.10.final\dist\target\wildfly-core-2.0.10.Final\modules,E:\workspace\sourceCode\wildfly-core-2.0.10.final\dist\target\wildfly-core-2.0.10.Final\modules\system\layers\base)))
        at org.jboss.logging.Logger$1.run(Logger.java:2556)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.jboss.logging.Logger.getMessageLogger(Logger.java:2529)
        at org.jboss.logging.Logger.getMessageLogger(Logger.java:2516)
        at org.jboss.as.server.logging.ServerLogger.<clinit>(ServerLogger.java:83)
        ... 6 more

java.util.concurrent.ExecutionException: Operation failed
        at org.jboss.threads.AsyncFutureTask.operationFailed(AsyncFutureTask.java:74)
        at org.jboss.threads.AsyncFutureTask.get(AsyncFutureTask.java:268)
        at org.jboss.as.server.Main.main(Main.java:103)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.modules.Module.run(Module.java:329)
        at org.jboss.modules.Main.main(Main.java:507)
Caused by: org.jboss.msc.service.StartException in service jboss.as: Failed to start service
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1904)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ExceptionInInitializerError
        at org.jboss.as.server.ApplicationServerService.start(ApplicationServerService.java:101)
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
        ... 3 more
Caused by: java.lang.IllegalArgumentException: Invalid logger interface org.jboss.as.server.logging.ServerLogger (implementation not found in ModuleClassLoader for Module "org.jboss.as.server:main" from local module loader @2280cdac (finder: local module finder @1517365b (roots: E:\workspace\sourceCode\wildfly-core-2.0.10.final\dist\target\wildfly-core-2.0.10.Final\modules,E:\workspace\sourceCode\wildfly-core-2.0.10.final\dist\target\wildfly-core-2.0.10.Final\modules\system\layers\base)))
        at org.jboss.logging.Logger$1.run(Logger.java:2556)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.jboss.logging.Logger.getMessageLogger(Logger.java:2529)
        at org.jboss.logging.Logger.getMessageLogger(Logger.java:2516)
        at org.jboss.as.server.logging.ServerLogger.<clinit>(ServerLogger.java:83)
        ... 6 more
07:51:21,745 ERROR [stderr] (Thread-2) Exception in thread "Thread-2" java.lang.NoClassDefFoundError: Could not initialize class org.jboss.as.server.logging.ServerLogger
07:51:21,755 ERROR [stderr] (Thread-2)  at org.jboss.as.server.BootstrapImpl$ShutdownHook.shutdown(BootstrapImpl.java:246)
07:51:21,762 ERROR [stderr] (Thread-2)  at org.jboss.as.server.BootstrapImpl$ShutdownHook.run(BootstrapImpl.java:228)

**Comment by kabir** [comment]
We don't use github issues.
You should ether use mailing list, user forums or file a jira report if you found bug.
See http://wildfly.org/gethelp/ for details where to get hold of team.
